### ISSUE TITLE
Topic /lidar3d/points not publishing

### ISSUE THREAD

**Issue by manuelgitgomes** [miguelriemoliveira/simpleBot#1]
Good afternoon @miguelriemoliveira.
Analtino and I were trying to run a calibration on our own. For that we were recording a bag file with simplebot, when we encountered a problem. The /lidar3d/points were no publishing, despite this lidar being called on the urdf and shown in the simulation. Instead, we had 2D lidar sensors publishing, as you can see on the picture.
![image](https://user-images.githubusercontent.com/58152228/144753401-6b1367ee-f6ab-43f3-91e7-7c2bb2c6a7c7.png)
The xaruco also does not appear on gazebo.
Do you have any idea on why this is?
Thank you for you attention

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

I assume that this is with gazebo running 

`roslaunch simplebot_gazebo simplebot.launch `

and 

`roslaunch simplebot_bringup bringup.launch`

right?

can you run a 

`rostopic echo`

to see if the lidar3d points have been advertised?

and then run a 

`rostopic hz <topic name>`

to see the frequency at which they are being published?

> The xaruco also does not appear on gazebo.

I do not understand what you mean ...

**Comment by manuelgitgomes** [comment]
> right?

Exactly, those were the commands used.

> to see if the lidar3d points have been advertised?

The topic is not publishing any message, both ```rostopic echo``` and ```rostopic hz``` warn me of that.

>I do not understand what you mean ...

While the xaruco appears on RVIZ, it does not appear on gazebo. So it's not shown by the camera images and the 2D lidar points. That's seen in the image.

![image](https://user-images.githubusercontent.com/58152228/144837053-3ff03162-4bcd-4606-82ac-59f8b4d802cd.png)

**Comment by manuelgitgomes** [comment]
Hello! I have no acess to this repo! Can you invite me?

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

I invited you and Analtino.

**Comment by manuelgitgomes** [comment]
Thank you!

**Comment by manuelgitgomes** [comment]
The issue is solved with the commit 16de3010a43101dbcb0d02ccd2ca9c62012f4c7c. It was also needed to install the velodyne-gazebo-plugins package with `sudo apt-get install ros-noetic-velodyne-gazebo-plugins`
