### ISSUE TITLE
Charuco not showing in Gazebo

### ISSUE THREAD

**Issue by DanielCoelho112** [miguelriemoliveira/simpleBot#5]
Hi @miguelriemoliveira, @manuelgitgomes, and @Analtino2021,

When I run these commands:

`roslaunch simplebot_gazebo simplebot.launch `

and

`roslaunch simplebot_bringup bringup.launch`

I get this:

![Screenshot from 2021-12-19 17-23-46](https://user-images.githubusercontent.com/73063947/146684498-5d4047ff-13f2-4dac-8c7a-bfb3716a25ba.png)

I think I have 2 problems:

1. The charuco isn't showing in gazebo
      I think @manuelgitgomes  was having this problem in #1, but the solution is not working for me.
2. Odometry Error:
  `Topic
Message contained invalid floating point values (nans or infs)`

Another thing I noticed is that the gazebo takes almost 20 seconds to spawn, this only happens with this world... Does this happen to anyone else?

@miguelriemoliveira  when you can, please put me as a collaborator.

**Comment by manuelgitgomes** [comment]
Hello! Im not currently at home, so I will look further into this later. The problem is that you are either misreferencing the charuco or it does not exist. That is why the gazebo takes so long to launch, it's searching for a file that is not there. Verify the references of your charuco, if you can't find the problem I will try and help you later

**Comment by miguelriemoliveira** [comment]
Thanks @manuelgitgomes .

I remember you had a similar problem. @DanielCoelho112 do you have this in your .bashrc?

`export GAZEBO_MODEL_PATH="`rospack find simplebot_gazebo`/models:${GAZEBO_MODEL_PATH}"`

**Comment by DanielCoelho112** [comment]
> @DanielCoelho112 do you have this in your .bashrc?

That was the problem!
Thanks @manuelgitgomes  and @miguelriemoliveira
